/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main()
{
    int n1=1,n2=2,n3,sum=2;
    long int x=4000000;
    //printf("%d\t%d\t",n1,n2);
    while(n3<x)
    {
        n3=n1+n2;    
        if(n3%2==0)
        sum=sum+n3;
        //printf("%d\t",n3);
        n1=n2;    
        n2=n3; 
        
    }
    printf("\n%d",sum);
    return 0;
}
